server:
  port: 8080
#  servlet:
#    context-path: /api/v1

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    password: 123
    username: postgres

  jpa:
    show-sql: true
    properties:
      hibernate:
        show_sql: true
    hibernate:
      ddl-auto: update